---

- hosts: all
  become: true
  tasks:
  
  - name: install the lastest version of httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: start httpd (CentOS)
    tags: apache, httpd, centos
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"
      
  - name: install the lastest version of Apache2
    tags: apache, apache2, ubuntu
    yum:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

 
